import { ErrorBoundary } from "@/components/ErrorBoundary";
import RuntimeConfigLoader from "@/components/RuntimeConfigLoader";
import ThemeProvider from "@/components/ThemeProvider";
import StarBackground from "@/components/StarBackground";
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import MiniAgentChatbot from "@/components/MiniAgentChatbot";
import AuthProvider from "@/components/auth/AuthProvider";
import ScrollToTop from "@/components/ui/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://agent.dosibridge.com"),
  title: {
    template: "%s | DosiBridge Agent",
    default: "DosiBridge Agent - Enterprise AI Assistant & RAG",
  },
  description:
    "DosiBridge Agent is an intelligent enterprise AI assistant by DosiBridge. Upload documents, leverage RAG technology, ask complex questions, and automate workflows securely.",
  keywords: [
    "DosiBridge",
    "DosiBridge Agent",
    "AI Agent",
    "RAG",
    "Document Analysis",
    "Enterprise AI",
    "AI Assistant",
    "Model Context Protocol",
  ],
  authors: [{ name: "DosiBridge", url: "https://dosibridge.com" }],
  creator: "DosiBridge",
  publisher: "DosiBridge",
  openGraph: {
    title: "DosiBridge Agent - Enterprise AI Assistant",
    description:
      "DosiBridge Agent is an intelligent AI assistant. Leverage RAG technology, ask questions, and get intelligent responses backed by your own knowledge base.",
    url: "https://agent.dosibridge.com",
    siteName: "DosiBridge Agent",
    images: [
      {
        url: "/opengraph-image", // Generated by app/opengraph-image.tsx
        width: 1200,
        height: 630,
        alt: "DosiBridge Agent Thumbnail",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    site: "@dosibridge",
    creator: "@dosibridge",
    title: "DosiBridge Agent - Enterprise AI Assistant",
    description:
      "DosiBridge Agent is an intelligent AI assistant. Leverage RAG technology, ask questions, and get intelligent responses backed by your own knowledge base.",
    images: ["/twitter-image"],
  },
  alternates: {
    canonical: "https://agent.dosibridge.com", // Main Google SEO canonical
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#030014] text-white min-h-screen relative`}
        suppressHydrationWarning
      >
        <StarBackground />

        {/* Initialize theme before React hydration to prevent flash */}
        <Script
          id="theme-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const stored = localStorage.getItem('theme');
                  // Force dark mode for space theme if needed, or stick to system
                  // For this UI overhaul, we prefer dark/space theme.
                  document.documentElement.classList.add('dark');
                } catch (e) {
                  document.documentElement.classList.add('dark');
                }
              })();
            `,
          }}
        />
        {/* Suppress console errors and network errors for blocked resources (e.g., ad blockers) */}
        <Script
          id="suppress-blocked-resource-errors"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                // Suppress console errors for blocked resources
                const originalError = console.error;
                const originalWarn = console.warn;
                const originalLog = console.log;

                // Override console methods to filter blocked resource errors
                console.error = function(...args) {
                  const message = args.join(' ');
                  if (message.includes('beacon.min.js') ||
                      message.includes('ERR_BLOCKED_BY_CLIENT') ||
                      message.includes('cloudflareinsights.com') ||
                      message.includes('static.cloudflareinsights.com') ||
                      message.includes('net::ERR_BLOCKED_BY_CLIENT')) {
                    return; // Suppress these errors
                  }
                  originalError.apply(console, args);
                };

                console.warn = function(...args) {
                  const message = args.join(' ');
                  if (message.includes('beacon.min.js') ||
                      message.includes('ERR_BLOCKED_BY_CLIENT') ||
                      message.includes('cloudflareinsights.com') ||
                      message.includes('static.cloudflareinsights.com') ||
                      message.includes('net::ERR_BLOCKED_BY_CLIENT')) {
                    return; // Suppress these warnings
                  }
                  originalWarn.apply(console, args);
                };

                console.log = function(...args) {
                  const message = args.join(' ');
                  if (message.includes('beacon.min.js') ||
                      message.includes('ERR_BLOCKED_BY_CLIENT') ||
                      message.includes('cloudflareinsights.com') ||
                      message.includes('static.cloudflareinsights.com') ||
                      message.includes('net::ERR_BLOCKED_BY_CLIENT')) {
                    return; // Suppress these logs
                  }
                  originalLog.apply(console, args);
                };

                // Suppress unhandled errors for blocked resources
                window.addEventListener('error', function(e) {
                  const errorMessage = e.message || e.filename || e.target?.src || '';
                  if (errorMessage.includes('beacon.min.js') ||
                      errorMessage.includes('ERR_BLOCKED_BY_CLIENT') ||
                      errorMessage.includes('cloudflareinsights.com') ||
                      errorMessage.includes('static.cloudflareinsights.com') ||
                      errorMessage.includes('net::ERR_BLOCKED_BY_CLIENT')) {
                    e.preventDefault();
                    e.stopPropagation();
                    e.stopImmediatePropagation();
                    return false;
                  }
                }, true);

                // Suppress network errors for blocked resources
                window.addEventListener('unhandledrejection', function(e) {
                  const reason = e.reason?.message || e.reason?.toString() || '';
                  if (reason.includes('beacon.min.js') ||
                      reason.includes('ERR_BLOCKED_BY_CLIENT') ||
                      reason.includes('cloudflareinsights.com') ||
                      reason.includes('static.cloudflareinsights.com') ||
                      reason.includes('net::ERR_BLOCKED_BY_CLIENT')) {
                    e.preventDefault();
                    return false;
                  }
                });

                // Intercept fetch requests to suppress errors for blocked resources
                const originalFetch = window.fetch;
                window.fetch = function(...args) {
                  const url = args[0]?.toString() || '';
                  if (url.includes('cloudflareinsights.com') ||
                      url.includes('beacon.min.js')) {
                    // Return a rejected promise that we'll catch
                    return Promise.reject(new Error('Blocked by ad blocker'));
                  }
                  return originalFetch.apply(this, args).catch(function(error) {
                    const errorMsg = error?.message || error?.toString() || '';
                    if (errorMsg.includes('ERR_BLOCKED_BY_CLIENT') ||
                        errorMsg.includes('cloudflareinsights.com') ||
                        errorMsg.includes('beacon.min.js')) {
                      // Suppress the error
                      return Promise.resolve(new Response(null, { status: 200 }));
                    }
                    throw error;
                  });
                };
              })();
            `,
          }}
        />
        <ThemeProvider />
        <RuntimeConfigLoader />
        <AuthProvider>
          <MiniAgentChatbot />
          <ScrollToTop />
          <ErrorBoundary>{children}</ErrorBoundary>
        </AuthProvider>
      </body>
    </html>
  );
}
