"""initial_schema

Revision ID: 35786e69cad8
Revises: 
Create Date: 2025-12-11 18:12:36.896116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35786e69cad8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_requests', sa.Column('guest_email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_api_requests_guest_email'), 'api_requests', ['guest_email'], unique=False)
    op.add_column('api_usage', sa.Column('guest_email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_api_usage_guest_email'), 'api_usage', ['guest_email'], unique=False)
    op.create_unique_constraint('uq_api_usage_guest_email_date', 'api_usage', ['guest_email', 'usage_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_api_usage_guest_email_date', 'api_usage', type_='unique')
    op.drop_index(op.f('ix_api_usage_guest_email'), table_name='api_usage')
    op.drop_column('api_usage', 'guest_email')
    op.drop_index(op.f('ix_api_requests_guest_email'), table_name='api_requests')
    op.drop_column('api_requests', 'guest_email')
    # ### end Alembic commands ###
